-- MySQL Script generated by MySQL Workbench
-- Wed Aug 10 22:15:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mp` ;

-- -----------------------------------------------------
-- Schema mp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mp` DEFAULT CHARACTER SET utf8 ;
USE `mp` ;

-- -----------------------------------------------------
-- Table `mp`.`fiscalia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mp`.`fiscalia` ;

CREATE TABLE IF NOT EXISTS `mp`.`fiscalia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `agency` VARCHAR(75) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(75) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  `town` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
